version: 2
updates:
  - package-ecosystem: "Docker"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50
    