version: "3"

services:

  whisper:
    image: ghcr.io/jo-hoe/whisper-docker-cli:latest
    container_name: whisper
    volumes:
      # read only right for input folder
      - ./input:/mnt/input:ro
      # rw right for output folder
      - ./output:/mnt/output
      # cache folder to store models between executions
      - ./cache:/root/.cache/whisper/

    # keep whisper running so one and exec into the container
    # the just attaches to the terminal
    tty: true         # same as to 'docker run -t ...'